### ISSUE TITLE
Optionally allow following symlinks

### ISSUE THREAD

**Issue by ebkalderon** [tailhook/openat#26]
It appears that `Dir::sub_dir()` always forces the `O_NOFOLLOW` flag when accessing files or subdirectories, which isn't always ideal. In my case, I was struggling to open the `/proc/self` subdirectory, until I eventually realized that I needed to perform the following dance to make it work:

```rust
let proc_dir = Dir::open("/proc")?;
// <snip>
let target = proc_dir.read_link("self")?;
let self_dir = proc_dir.sub_dir(&target)?;
```

This was surprising, as this was inconsistent with the default behavior of `openat()` and the IO error it produces was initially mystifying (it simply stated "Not a directory").

It would be nice if users could specify with a boolean flag on `sub_dir()` whether they would like to follow symlinks or not. At the very least, I think the documentation for `sub_dir()` should mention that symlinked subdirectories require the use of `read_link()` to resolve the real path before attempting to access it.

**Comment by tailhook** [comment]
I'm happy to accept PR for a documentation update. 

For the flag: I think we should do that at some point. But we must do it considering #18 and #25 too. (i.e. some "open with options" method). So I'm not sure I can allocate time for it soon.

Just to know the context: any specific reason you're using `openat` for `/proc/self` ? I mean what's the benefit comparing to just opening `/proc/self` directly?

**Comment by ebkalderon** [comment]
Sounds good! I'd be happy to open a PR with just the documentation update for now and close this issue in favor of #18, since I believe its scope encompasses this one.

In the sandboxing library I'm developing, I open the `/proc` directory with `Dir::open()` and keep the file descriptor open so that I can pass it into one or more child process, which needs access to various elements of `/proc` at different times. Sometimes I look at a specific PID under `/proc`, other times I look at `/proc/self` depending on what task the child needs to accomplish.

Because of this, I chose to keep a lone file descriptor for `/proc` open in the parent process and pass it to the child processes to use as they wish while setting up their environments, and it is easy to revoke privileges and drop inherited file descriptors before calling `exec()` on the desired process to sandbox because there is only one to manage.

With that said, I'm still polishing and simplifying this architecture, so it isn't final.
