### ISSUE TITLE
Checking version of from_raw_fd

### ISSUE THREAD

**Issue by shlevy** [tailhook/openat#30]
In cases where a file descriptor is provided from a parent process or over a socket, we might get a non-directory fd. If you just use `from_raw_fd` on it, you'll only find out when you try to use the resulting `Dir`, which might make it harder to provide a nice fail-early error message. I recommend:

1. Add impl-specific documentation to the `Dir` implementation of `from_raw_fd` noting that the user should guarantee the fd is a directory first
2. Add a `from_raw_fd_checked` or similar that handles this check for the user (using `fstat`), returning an `Option`.

**Comment by tailhook** [comment]
Sounds good. Do you want to make a PR?
