### ISSUE TITLE
Dir: please provide open<File> and open<Fd>

### ISSUE THREAD

**Issue by lucab** [tailhook/openat#7]
Sometimes I find myself in situations where I only have a pre-opened `RawFd` or `File` handle to a directory. I think it would be helpful to provide here some (fallible) constructors so that I can upgrade those to real `Dir`.

Did I maybe miss something, and this is already implemented or maybe not feasible at all? Ah, and thanks for this crate!

**Comment by tailhook** [comment]
Sure. We should implement `FromRawFd`. Seems easy. Do you want to make a PR?

**Comment by lucab** [comment]
I'll be happy to, but I can't guarantee any timeline. If anybody is quicker than me here, please go ahead.

With some more details: `FromRawFd` cannot fail, but not all fd are valid dirfd. I was actually thinking of doing a `fstat` and return and `Err` on anything which is not a `S_IFDIR`, thus having a `open(fd) -> Result<Dir>`. Thoughts?

**Comment by tailhook** [comment]
What is a use case of passing unknown file descriptors?

I mean, you can also pass a directory file descriptor to `File::FromRawFd`, and next read/write will fail, but this has never been an issue, for me at least. Usually, It's the responsibility of a user to do needed check and/or pass right file descriptors.

This is also consistent with the current behavior. You can use `Dir::open("filename.txt")` on a file.

By the way, you can check fd after creation with `dir.sub_dir(".")`, not sure it a good method to recommend, though.

**Comment by lucab** [comment]
I was assuming that `Dir::open("filename.txt")` would return an `Err` (as the internal fd is not a dirfd then), but looking at the code it seems that my assumption was wrong.

The usecase is not to pass unknown file descriptor, but to let typesystem ensure that `Dir` holds a directory (i.e. dirfd) and not anything generic (i.e. a socket).

**Comment by tailhook** [comment]
As you can see in e65cc9e it wasn't hard :) Done and released in `v0.1.14`
